models/Item.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "item".
 *
 * @property integer $id
 * @property string $title
 * @property integer $type
 * @property integer $morning
 * @property integer $afternoon
 * @property integer $night
 * @property integer $anytime
 * @property string $timestamp
 *
 * @property Image[] $images
 * @property ItemItems[] $itemItems
 */
class Item extends ActiveRecord
{
	public $times = [];

	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'item';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['title', 'type'], 'required'],
			[['title'], 'trim'],
			[['title'], 'string', 'max' => 70],
			[['title'], 'unique'],
			[['title'], 'caseInsensitiveUnique', 'except' => ['update']],
			[['type'], 'integer'],
			[['type'], 'in', 'range' => [0, 1]],
			[['times'], 'safe']
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'title' => 'Title',
			'type' => 'Type',
			'morning' => 'Morning',
			'afternoon' => 'Afternoon',
			'night' => 'Night',
			'anytime' => 'Anytime',
			'timestamp' => 'Timestamp',
			'times' => 'Time'
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getImages()
	{
		return $this->hasMany(Image::className(), ['item_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getItemItems()
	{
		return $this->hasMany(ItemItem::className(), ['id2' => 'id']);
	}

	public function caseInsensitiveUnique($attribute)
	{
		$query = (new \yii\db\Query)
			->select(['id'])
			->from(Item::tableName())
			->where('lower(title)=:title', [':title' => strtolower($this->title)])
			->exists();

		if ($query)
			$this->addError($attribute, 'Title "'.$this->title.'" has already been taken.');
	}
}

controllers/ImageController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Image;
use app\models\ImageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\imagine\Image as Imagine;

/**
 * ImageController implements the CRUD actions for Image model.
 */
class ImageController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index','view','wall','submit','update','delete'],
				'rules' => [
					[
						'allow' => true,
						'actions' => ['submit']
					],
					[
						'allow' => true,
						'actions' => ['index','view','wall','update','delete'],
						'roles' => ['@'],
					],
				],
				'denyCallback' => function ($rule, $action) {
					throw new NotFoundHttpException('The requested page does not exist.');
				}
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}

	/**
	 * Lists all Image models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new ImageSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single Image model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		$imageRow = (new Query)
			->select(['id','item_id','file'])
			->from(Image::tableName())
			->where('id=:id', [':id' => $id])
			->one();
		if (!$imageRow)
			throw new NotFoundHttpException('The requested page does not exist.');

		$itemRow = (new Query)
			->select('title')
			->from('item')
			->where('id=:id', [':id' => $imageRow['item_id']])
			->one();
		if (!$itemRow)
			throw new NotFoundHttpException('The requested page does not exist.');

		return $this->render('view', [
			'model' => $imageRow,
			'title' => $itemRow['title']
		]);
	}

	public function actionWall($id)
	{
		$imageRows = (new Query)
			->select(['id','file'])
			->from(Image::tableName())
			->where('item_id=:item_id', [':item_id' => $id])
			->all();

		$itemRow = (new Query)
			->select('title')
			->from('item')
			->where('id=:id', [':id' => $id])
			->one();

		return $this->render('wall', [
			'models' => $imageRows,
			'title' => $itemRow['title'],
			'item_id' => $id
		]);
	}

	/**
	 * Creates a new Image model.
	 * If creation is successful, the browser will be redirected to the 'item/view' page.
	 * @return mixed
	 */
	public function actionSubmit($id, $title)
	{
		$model = new Image;

		if (Yii::$app->user->isGuest)
			$model->setScenario('guestSubmit');
		else
			$model->setScenario('adminSubmit');

		if (Yii::$app->request->post())
		{
			$models = [];
			$files = UploadedFile::getInstances($model, 'file');

			foreach ($files as $file)
			{
				$model = new Image;
				$model->item_id = $id;
				$model->file = $file;
				$models[] = $model;
			}

			// All or nothing image saving.
			foreach ($models as $model)
				if (!$model->validate() || !$model->file || $model->file->hasError)
					return $this->render('submit', [
						'model' => $model,
						'id' => $id,
						'title' => $title
					]);

			// All images are valid and have passed all tests.
			foreach ($models as $i => $model)
			{
				$model->file = $id.date('_Ymd_His_').substr((string)microtime(), 2, 6).'.'.$files[$i]->extension;
				if ($model->save(false))
				{
					$files[$i]->saveAs('uploads/'.$model->file);

					Imagine::thumbnail('uploads/'.$model->file, 150, 150)
						->save('uploads/thumbnails/150x150_'.$model->file, ['quality' => 50]);

					Imagine::thumbnail('uploads/'.$model->file, 64, 64)
						->save('uploads/thumbnails/64x64_'.$model->file, ['quality' => 50]);
				}
			}

			return $this->redirect(['item/view', 'id' => $id, 'title' => $title]);
		}
		else
			return $this->render('submit', [
				'model' => $model,
				'id' => $id,
				'title' => $title
			]);
	}

	/**
	 * Updates an existing Image model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = Image::find()
			->select(['id','file'])
			->where('id=:id', [':id' => $id])
			->one();
		if (!$model)
			throw new NotFoundHttpException('The requested page does not exist.');

		$model->setScenario('update');

		if (Yii::$app->request->post())
		{
			$current_file = $model->file;
			$file_name = substr($model->file, 0, strpos($model->file, '.'));

			$file = UploadedFile::getInstance($model,'file');

			if ($file && !$file->hasError)
				$model->file = $file;

			if (!$model->validate())
				return $this->render('update', ['model' => $model]);

			$model->file = $file_name.'.'.$file->extension;

			if ($model->save(false))
			{
				unlink('uploads/'.$current_file);
				unlink('uploads/thumbnails/150x150_'.$current_file);
				unlink('uploads/thumbnails/64x64_'.$current_file);

				$file->saveAs('uploads/'.$model->file);

				Imagine::thumbnail('uploads/'.$model->file, 150, 150)
					->save('uploads/thumbnails/150x150_'.$model->file, ['quality' => 50]);

				Imagine::thumbnail('uploads/'.$model->file, 64, 64)
					->save('uploads/thumbnails/64x64_'.$model->file, ['quality' => 50]);
			}

			return $this->redirect(['view', 'id' => $model->id]);
		}
		else
			return $this->render('update', ['model' => $model]);
	}

	/**
	 * Deletes an existing Image model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id, $direct = null)
	{
		$model = Image::find()
			->select(['id','item_id','file'])
			->where('id=:id', [':id' => $id])
			->with([
				'item' => function($query) {
					$query->select('title');
				}
			])
			->one();
		if (!$model)
			throw new NotFoundHttpException('The requested page does not exist.');

		$item_id = $model->item_id;
		$file = $model->file;
		$title = $model->item->title;

		if ($model->delete())
		{
			unlink('uploads/'.$file);
			unlink('uploads/thumbnails/150x150_'.$file);
			unlink('uploads/thumbnails/64x64_'.$file);
		}

		if ($direct)
			return $this->redirect(['wall', 'id' => $item_id, 'title' => $title]);
		else
			return $this->redirect(['index']);
	}
}

controllers/ItemItemController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ItemItem;
use app\models\ItemItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use yii\filters\AccessControl;

/**
 * ItemItemController implements the CRUD actions for ItemItem model.
 */
class ItemItemController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index','view','link','update','delete'],
				'rules' => [
					[
						'allow' => true,
						'actions' => ['link']
					],
					[
						'allow' => true,
						'actions' => ['index','view','update','delete'],
						'roles' => ['@'],
					],
				],
				'denyCallback' => function ($rule, $action) {
					throw new NotFoundHttpException('The requested page does not exist.');
				}
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}

	/**
	 * Lists all ItemItem models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new ItemItemSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single ItemItem model.
	 * @param integer $id1
	 * @param integer $id2
	 * @return mixed
	 */
	public function actionView($id1, $id2)
	{
		$titles = [];

		// Query Builder – Quick performance and concise presentation in this case. Seven lines of code.
		$row = (new Query)
			->select('title')
			->from('item')
			->where('id=:id', [':id' => $id1])
			->one();
		if (!$row)
			throw new NotFoundHttpException('The requested page does not exist.');

		$titles[] = $row['title'];

		// Raw SQL – The fastest, but takes more work. Nine lines of code. A little harder to read.
		$itemSQL = Yii::$app->db->createCommand('
			SELECT title
			FROM item
			WHERE id = :id
		');
		$itemSQL->bindValue(':id', $id2);

		$row = $itemSQL->queryOne();
		if (!$row)
			throw new NotFoundHttpException('The requested page does not exist.');

		$titles[] = $row['title'];

		return $this->render('view', ['model' => $this->findModel($id1, $id2), 'titles' => $titles]);
	}

	public function actionLink($id, $title)
	{
		$model = new ItemItem();

		$linkableItems = $this->getLinkableItems($id);

		if ($model->load(Yii::$app->request->post()))
		{
			if ($model->links)
			{
				$models = [];

				foreach ($model->links as $link)
				{
					$model = new ItemItem();
					$model->id1 = $id;
					$model->id2 = $link;
					$models[] = $model;
				}

				// All or nothing link checking.
				foreach ($models as $model)
					if (!$model->validate())
						return $this->render('link', [
							'model' => $model,
							'id' => $id,
							'title' => $title,
							'linkableItems' => $linkableItems
						]);

				// All links are valid and have passed all tests.
				foreach ($models as $model)
					$model->save(false);

				return $this->redirect(['item/view', 'id' => $id, 'title' => $title]);
			}
			else
				return $this->redirect(['item/view', 'id' => $id, 'title' => $title]);
		}
		else
			return $this->render('link', [
				'model' => $model,
				'id' => $id,
				'title' => $title,
				'linkableItems' => $linkableItems
			]);
	}

	private function getLinkableItems($id)
	{
		$items = [];

		$itemSQL = Yii::$app->db->createCommand('
			SELECT id, title
			FROM item
			WHERE id <> :id
				AND	id NOT IN (SELECT id1 FROM item_item WHERE id2 = :id2)
				AND	id NOT IN (SELECT id2 FROM item_item WHERE id1 = :id1)
			ORDER BY title
		');
		$itemSQL->bindValue(':id', $id);
		$itemSQL->bindValue(':id1', $id);
		$itemSQL->bindValue(':id2', $id);
		$itemRows = $itemSQL->queryAll();

		foreach ($itemRows as $row)
			$items[$row['id']] = $row['title'];

		return $items;
	}

	/**
	 * Updates an existing ItemItem model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id1
	 * @param integer $id2
	 * @return mixed
	 */
	public function actionUpdate($id1, $id2)
	{

		return $this->redirect(['index']);
		// skip everything below

		// $model = $this->findModel($id1, $id2);

		// if ($model->load(Yii::$app->request->post()) && $model->save())
		// 	return $this->redirect(['view', 'id1' => $model->id1, 'id2' => $model->id2]);
		// else
		// 	return $this->render('update', ['model' => $model]);
	}

	/**
	 * Deletes an existing ItemItem model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id1
	 * @param integer $id2
	 * @return mixed
	 */
	public function actionDelete($id1, $id2)
	{
		$this->findModel($id1, $id2)->delete();

		return $this->redirect(['index']);
	}

	/**
	 * Finds the ItemItem model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id1
	 * @param integer $id2
	 * @return ItemItem the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id1, $id2)
	{
		if (($model = ItemItem::findOne(['id1' => $id1, 'id2' => $id2])) !== null)
			return $model;
		else
			throw new NotFoundHttpException('The requested page does not exist.');
	}
}

views/item/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\SwitchInput;

/* @var $this yii\web\View */
/* @var $model app\models\Item */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-form">

	<?php $form = ActiveForm::begin(['options' => ['autocomplete'=>'off']]); ?>

	<?= $form->field($model, 'title')->textInput(['maxlength' => 70]) ?>

	<?= $form->field($model, 'type')->widget(SwitchInput::classname(), [
		'pluginOptions' => [
			'size' => 'small',
			'onText' => 'drink',
			'offText' => 'food'
		],
		'inlineLabel' => false,
	]); ?>

	<?php if ($model->isNewRecord): ?>
	<?= $form->field($model, 'times')->checkboxList(['morning' => 'morning', 'afternoon' => 'afternoon', 'night' => 'night'],
	 ['separator' => '<br>']); ?>
	<?php endif ?>

	<div class="form-group">
		<?= Html::submitButton($model->isNewRecord ? 'Submit' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-info']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

views/item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'morning') ?>

    <?= $form->field($model, 'afternoon') ?>

    <?php // echo $form->field($model, 'night') ?>

    <?php // echo $form->field($model, 'anytime') ?>

    <?php // echo $form->field($model, 'timestamp') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/item/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Items - '.Yii::$app->params['app'];
?>
<div class="item-index">

	<p class='pull-right'>
		<?= Html::a('Submit Item', ['submit'], ['class' => 'btn btn-success']) ?>
		<?= Html::a('Items', ['item/index'], ['class' => 'btn btn-purple']) ?>
		<?= Html::a('Images', ['image/index'], ['class' => 'btn btn-black']) ?>
		<?= Html::a('Links', ['item-item/index'], ['class' => 'btn btn-warning']) ?>
	</p>

	<h1>Items</h1>

	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'columns' => [
			['class' => 'yii\grid\SerialColumn'],

			'id',
			'title',
			'type',
			'morning',
			'afternoon',
			'night',
			'anytime',
			'timestamp',

			['class' => 'yii\grid\ActionColumn'],
		],
	]); ?>

</div>

views/item/list.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model app\models\SimpleItem */
/* @var $items all the items in the db */
/* @var $dataProvider yii\data\ArrayDataProvider */

$this->title = 'List - '.Yii::$app->params['app'];
?>
<?php $this->registerJS("$('#inspect').tooltip();"); ?>

<div class="item-list">

	<p class='pull-right'>
		<?= Html::a('Submit Item', ['submit'], ['class' => 'btn btn-success']) ?>
	</p>

	<h1>List</h1>
	<h5>The List shows all the items that exist in the database.</h5>

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'id')->widget(Select2::classname(), [
		'data' => $items,
		'size' => 'sm',
		'options' => ['placeholder' => 'Search'],
		'pluginOptions' => [
			'allowClear' => true,
			'maximumInputLength' => 70
		],
		'addon' => ['append' => [
			'content' => Html::submitButton("<span class='glyphicon glyphicon-search'></span>", [
				'class' => 'btn btn-primary',
				'id' => 'inspect',
				'data-toggle' => 'tooltip',
				'title' => 'Inspect'
			]),
			'asButton' => true
		]]
	]); ?>

	<?php ActiveForm::end(); ?>

	<?= ListView::widget([
		'dataProvider' => $dataProvider,
		'itemOptions' => ['class' => 'item'],
		'itemView' => function ($model, $key, $index, $widget) {
			return Html::a(Html::encode($model['title']), ['view', 'id' => $model['id'], 'title' => $model['title']]);
		}
	]) ?>

</div>

views/item/submit.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $model app\models\Item */

$this->title = 'Submit Item - '.Yii::$app->params['app'];
?>
<div class="item-submit">

	<h1>Submit Item</h1>
	<h5>Before submitting, please make sure the item doesn't already exist in the database by checking out the
	<a href='<?= Url::to(['item/list']) ?>'>List</a>.</h5>

	<?= $this->render('_form', ['model' => $model]) ?>

</div>

views/item/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Item */

$this->title = 'Update Item - '.Yii::$app->params['app'];
?>
<div class="item-update">

	<h1>Update Item</h1>

	<p>
		<?= Html::a($model->title, ['view', 'id' => $model->id, 'title' => $model->title], ['class' => 'btn btn-default']) ?>
		<?= Html::a('Index', ['index'], ['class' => 'btn btn-light-purple']) ?>
	</p>

	<?= $this->render('_form', ['model' => $model]) ?>

</div>

views/item/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Item */
/* @var $votes votes */
/* @var $percents percents */
/* @var $images images */
/* @var $links links */

$this->title = $model['title'].' - '.Yii::$app->params['app'];
?>
<?php if ($images): ?>
<?php $this->registerCssFile('//cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.2/fotorama.css') ?>
<?php $this->registerJsFile('//cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.2/fotorama.js', ['depends' => ['yii\web\JqueryAsset']]) ?>
<?php endif ?>

<div class="item-view">
	<article>
		<p id='controls'>
			<?= Html::a('Vote', ['vote', 'id' => $model['id'], 'title' => $model['title']], ['class' => 'btn btn-primary']) ?>
			<?= Html::a('Submit image', ['image/submit', 'id' => $model['id'], 'title' => $model['title']], ['class' => 'btn btn-success']) ?>
			<?= Html::a('Link item', ['item-item/link', 'id' => $model['id'], 'title' => $model['title']], ['class' => 'btn btn-purple']) ?>
		<?php if (!Yii::$app->user->isGuest): ?>
			<?= Html::a('Update', ['update', 'id' => $model['id']], ['class' => 'btn btn-info']) ?>
			<?= Html::a('Images', ['image/wall', 'id' => $model['id']], ['class' => 'btn btn-black']) ?>
			<?= Html::a('Delete', ['delete', 'id' => $model['id']], [
				'class' => 'btn btn-danger',
				'data' => [
					'confirm' => 'Are you sure you want to delete this item?',
					'method' => 'post',
				],
			]) ?>
			<?= Html::a('Index', ['index'], ['class' => 'btn btn-light-purple']) ?>
		<?php endif ?>
		</p>

		<h1><?= Html::encode($model['title']) ?></h1>

		<h2><?= Html::encode(number_format($votes)).' '.(($votes===1)?'vote':'votes') ?></h2>
		<h4>
			<span><?= Html::encode($percents['morning']) ?>% morning |</span>
			<span><?= Html::encode($percents['afternoon']) ?>% afternoon |</span>
			<span><?= Html::encode($percents['night']) ?>% night |</span>
			<span><?= Html::encode($percents['anytime']) ?>% anytime</span>
		</h4>

		<div align='center' class='fotorama'
			data-keyboard='{"space": true, "home": true, "end": true, "left": true, "right": true}'
			data-navposition='bottom' data-loop='true' data-nav='thumbs'
			data-maxheight='400' data-width='100%' data-ratio='16/9'>
			<?php
			if ($images)
				foreach ($images as $image)
					if ($image): ?>
						<a href="<?= Yii::$app->request->hostInfo.'/uploads/'.Html::encode($image['file']) ?>">
							<img src="<?= Yii::$app->request->hostInfo.'/uploads/thumbnails/64x64_'.Html::encode($image['file']) ?>" alt='<?= Html::encode($model['title']) ?>'>
						</a>
					<?php endif	?>
		</div>

	<?php if ($links): ?>
		<hr>

		<h4>Linked Items</h4>

		<div class="row">
	<?php foreach ($links as $id => $link): ?>
	<?php $this->registerJS("$('#link".Html::encode($id)."').tooltip();"); ?>
			<div class="col-md-1 col-sm-2 col-xs-6" id="link<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($link->title) ?>">
				<a href="<?= Html::encode(Url::to(['view', 'id' => $id, 'title' => $link->title])) ?>" class="thumbnail">
	<?php if ($link->file): ?>
					<img src="<?= Yii::$app->request->hostInfo.'/uploads/thumbnails/150x150_'.Html::encode($link->file) ?>" alt='<?= Html::encode($link->title) ?>'>
	<?php else: ?>
					<img src="<?= Yii::$app->request->hostInfo.'/placeholder.png' ?>" alt='No Image'>
	<?php endif ?>
				</a>
			</div>
	<?php endforeach ?>
		</div>
	<?php endif ?>
	</article>

	<div id="disqus_thread"></div>
	<script type="text/javascript">
		/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
		var disqus_shortname = 'eatdrinktime'; // required: replace example with your forum shortname
		var disqus_identifier = '<?= Html::encode($model['id']) ?>';
		var disqus_title = '<?= Html::encode($model['title']) ?>';
		var disqus_url = "<?= Html::encode(Url::to(['view', 'id' => $model['id'], 'title' => $model['title']], true)) ?>";

		/* * * DON'T EDIT BELOW THIS LINE * * */
		(function() {
			var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
			dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

</div>

views/item/vote.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Vote */
/* @var $id item id */
/* @var $title item title */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Vote on '.$title.' - '.Yii::$app->params['app'];
?>
<div class="item-vote">

	<h1>Vote</h1>
	<h5>What time do you normally consume this item?<br>Each check mark counts as a vote.<br>When all three boxes are checked, a single vote will be placed for anytime.</h5>

	<p><?= Html::a($title, ['view', 'id' => $id, 'title' => $title], ['class' => 'btn btn-default']) ?></p>

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'times')->checkboxList(['morning' => 'morning', 'afternoon' => 'afternoon', 'night' => 'night'],
	 ['separator' => '<br>']); ?>

	<div class="form-group">
		<?= Html::submitButton('Vote', ['class' => 'btn btn-primary']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>