controllers/ImageController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Image;
use app\models\ImageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\imagine\Image as Imagine;

/**
 * ImageController implements the CRUD actions for Image model.
 */
class ImageController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index','view','wall','submit','update','delete'],
				'rules' => [
					[
						'allow' => true,
						'actions' => ['submit']
					],
					[
						'allow' => true,
						'actions' => ['index','view','wall','update','delete'],
						'roles' => ['@'],
					],
				],
				'denyCallback' => function ($rule, $action) {
					throw new NotFoundHttpException('The requested page does not exist.');
				}
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}

	/**
	 * Lists all Image models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new ImageSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single Image model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		$imageRow = (new Query)
			->select(['id','item_id','file'])
			->from(Image::tableName())
			->where('id=:id', [':id' => $id])
			->one();
		if (!$imageRow)
			throw new NotFoundHttpException('The requested page does not exist.');

		$itemRow = (new Query)
			->select('title')
			->from('item')
			->where('id=:id', [':id' => $imageRow['item_id']])
			->one();
		if (!$itemRow)
			throw new NotFoundHttpException('The requested page does not exist.');

		return $this->render('view', [
			'model' => $imageRow,
			'title' => $itemRow['title']
		]);
	}

	public function actionWall($id)
	{
		$imageRows = (new Query)
			->select(['id','file'])
			->from(Image::tableName())
			->where('item_id=:item_id', [':item_id' => $id])
			->all();

		$itemRow = (new Query)
			->select('title')
			->from('item')
			->where('id=:id', [':id' => $id])
			->one();

		return $this->render('wall', [
			'models' => $imageRows,
			'title' => $itemRow['title'],
			'item_id' => $id
		]);
	}

	/**
	 * Creates a new Image model.
	 * If creation is successful, the browser will be redirected to the 'item/view' page.
	 * @return mixed
	 */
	public function actionSubmit($id, $title)
	{
		$model = new Image;

		if (Yii::$app->user->isGuest)
			$model->setScenario('guestSubmit');
		else
			$model->setScenario('adminSubmit');

		if (Yii::$app->request->post())
		{
			$models = [];
			$files = UploadedFile::getInstances($model, 'file');

			foreach ($files as $file)
			{
				$model = new Image;
				$model->item_id = $id;
				$model->file = $file;
				$models[] = $model;
			}

			// All or nothing image saving.
			foreach ($models as $model)
				if (!$model->validate() || !$model->file || $model->file->hasError)
					return $this->render('submit', [
						'model' => $model,
						'id' => $id,
						'title' => $title
					]);

			// All images are valid and have passed all tests.
			foreach ($models as $i => $model)
			{
				$model->file = $id.date('_Ymd_His_').substr((string)microtime(), 2, 6).'.'.$files[$i]->extension;
				if ($model->save(false))
				{
					$files[$i]->saveAs('uploads/'.$model->file);

					Imagine::thumbnail('uploads/'.$model->file, 150, 150)
						->save('uploads/thumbnails/150x150_'.$model->file, ['quality' => 50]);

					Imagine::thumbnail('uploads/'.$model->file, 64, 64)
						->save('uploads/thumbnails/64x64_'.$model->file, ['quality' => 50]);
				}
			}

			return $this->redirect(['item/view', 'id' => $id, 'title' => $title]);
		}
		else
			return $this->render('submit', [
				'model' => $model,
				'id' => $id,
				'title' => $title
			]);
	}

	/**
	 * Updates an existing Image model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = Image::find()
			->select(['id','file'])
			->where('id=:id', [':id' => $id])
			->one();
		if (!$model)
			throw new NotFoundHttpException('The requested page does not exist.');

		$model->setScenario('update');

		if (Yii::$app->request->post())
		{
			$current_file = $model->file;
			$file_name = substr($model->file, 0, strpos($model->file, '.'));

			$file = UploadedFile::getInstance($model,'file');

			if ($file && !$file->hasError)
				$model->file = $file;

			if (!$model->validate())
				return $this->render('update', ['model' => $model]);

			$model->file = $file_name.'.'.$file->extension;

			if ($model->save(false))
			{
				unlink('uploads/'.$current_file);
				unlink('uploads/thumbnails/150x150_'.$current_file);
				unlink('uploads/thumbnails/64x64_'.$current_file);

				$file->saveAs('uploads/'.$model->file);

				Imagine::thumbnail('uploads/'.$model->file, 150, 150)
					->save('uploads/thumbnails/150x150_'.$model->file, ['quality' => 50]);

				Imagine::thumbnail('uploads/'.$model->file, 64, 64)
					->save('uploads/thumbnails/64x64_'.$model->file, ['quality' => 50]);
			}

			return $this->redirect(['view', 'id' => $model->id]);
		}
		else
			return $this->render('update', ['model' => $model]);
	}

	/**
	 * Deletes an existing Image model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id, $direct = null)
	{
		$model = Image::find()
			->select(['id','item_id','file'])
			->where('id=:id', [':id' => $id])
			->with([
				'item' => function($query) {
					$query->select('title');
				}
			])
			->one();
		if (!$model)
			throw new NotFoundHttpException('The requested page does not exist.');

		$item_id = $model->item_id;
		$file = $model->file;
		$title = $model->item->title;

		if ($model->delete())
		{
			unlink('uploads/'.$file);
			unlink('uploads/thumbnails/150x150_'.$file);
			unlink('uploads/thumbnails/64x64_'.$file);
		}

		if ($direct)
			return $this->redirect(['wall', 'id' => $item_id, 'title' => $title]);
		else
			return $this->redirect(['index']);
	}
}

controllers/ItemController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Item;
use app\models\ItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use app\models\Image;
use app\models\ItemItem;
use app\models\ListItem;
use app\models\Vote;
use yii\data\ArrayDataProvider;
use app\models\SimpleItem;
use yii\filters\AccessControl;

/**
 * ItemController implements the CRUD actions for Item model.
 */
class ItemController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index','list','view','submit','vote','update','delete'],
				'rules' => [
					[
						'allow' => true,
						'actions' => ['list','view','submit','vote']
					],
					[
						'allow' => true,
						'actions' => ['index','update','delete'],
						'roles' => ['@'],
					],
				],
				'denyCallback' => function ($rule, $action) {
					throw new NotFoundHttpException('The requested page does not exist.');
				}
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}

	/**
	 * Lists all Item models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new ItemSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionList()
	{
		$model = new ListItem;

		$items = [];
		$dataProvider;

		if ($model->load(Yii::$app->request->post()))
			if ($model->id)
				return $this->redirect(['view', 'id' => $model->id]);
			else
				$this->listHelper($items, $dataProvider);
		else
			$this->listHelper($items, $dataProvider);

		return $this->render('list', ['model' => $model, 'items' => $items, 'dataProvider' => $dataProvider]);
	}

	private function listHelper(&$items, &$dataProvider)
	{
		$itemRows = Yii::$app->db->createCommand('
			SELECT id, title
			FROM item
			ORDER BY title
		')->queryAll();

		foreach ($itemRows as $row)
			$items[$row['id']] = $row['title'];

		$dataProvider = new ArrayDataProvider([
			'allModels' => $itemRows,
			'pagination' => ['pageSize' => 20]
		]);
	}

	/**
	 * Displays a single Item model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		$itemSQL = Yii::$app->db->createCommand('
			SELECT id, title, morning, afternoon, night, anytime
			FROM item
			WHERE id = :id
		');
		$itemSQL->bindValue(':id', $id);
		$itemRow = $itemSQL->queryOne();
		if (!$itemRow)
			throw new NotFoundHttpException('The requested page does not exist.');

		$votes = $itemRow['morning'] + $itemRow['afternoon'] + $itemRow['night'] + $itemRow['anytime'];

		if ($votes === 0)
			$percents = ['morning' => 0, 'afternoon' => 0, 'night' => 0, 'anytime' => 0];
		else
		{
			$percents = [
				'morning' => $itemRow['morning'] / $votes * 100,
				'afternoon' => $itemRow['afternoon'] / $votes * 100,
				'night' => $itemRow['night'] / $votes * 100,
				'anytime' => $itemRow['anytime'] / $votes * 100
			];

			foreach ($percents as $i => $percent)
				if (is_float($percent) && (floor($percent) !== $percent))
					$percents[$i] = number_format($percent, 1);
		}

		// PostgreSQL
		// $imageSQL = Yii::$app->db->createCommand('
		// 	SELECT file
		// 	FROM image
		// 	WHERE item_id = :item_id
		// 	ORDER BY RANDOM()
		// ');

		// MariaDB
		$imageSQL = Yii::$app->db->createCommand('
			SELECT file
			FROM image
			WHERE item_id = :item_id
			ORDER BY RAND()
		');
		$imageSQL->bindValue(':item_id', $id);
		$images = $imageSQL->queryAll();

		return $this->render('view', [
			'model' => $itemRow,
			'votes' => $votes,
			'percents' => $percents,
			'images' => $images,
			'links' => $this->getLinkItems($id)
		]);
	}

	private function getLinkItems($id)
	{
		$links = [];

		$itemSQL = Yii::$app->db->createCommand('
			SELECT id, title
			FROM item
			WHERE id <> :id AND (
				id IN (SELECT id1 FROM item_item WHERE id2 = :id2)
				OR
				id IN (SELECT id2 FROM item_item WHERE id1 = :id1)
			)
			ORDER BY title
		');
		$itemSQL->bindValue(':id', $id);
		$itemSQL->bindValue(':id1', $id);
		$itemSQL->bindValue(':id2', $id);
		$itemLinkRows = $itemSQL->queryAll();

		foreach ($itemLinkRows as $row)
		{
			// PostgreSQL
			// $imageSQL = Yii::$app->db->createCommand('
			// 	SELECT file
			// 	FROM image
			// 	WHERE item_id = :id
			// 	ORDER BY RANDOM()
			// 	LIMIT 5
			// ');

			// MariaDB
			$imageSQL = Yii::$app->db->createCommand('
				SELECT file
				FROM image
				WHERE item_id = :id
				ORDER BY RAND()
				LIMIT 5
			');
			$imageSQL->bindValue(':id', $row['id']);
			$imageRows = $imageSQL->queryAll();

			$links[$row['id']] = new SimpleItem;
			$links[$row['id']]->title = $row['title'];

			if ($imageRows)
				$links[$row['id']]->file = $imageRows[0]['file'];
			else
				$links[$row['id']]->file = null;
		}

		return $links;
	}

	/**
	 * Creates a new Item model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionSubmit()
	{
		$model = new Item();

		if ($model->load(Yii::$app->request->post()))
		{
			if ($model->times)
			{
				if (count($model->times) === 3)
					$model->anytime += 1;
				else
					foreach ($model->times as $time)
						switch ($time)
						{
							case 'morning':
								$model->morning += 1;
								break;
							case 'afternoon':
								$model->afternoon += 1;
								break;
							case 'night':
								$model->night += 1;
								break;
						}
			}

			$model->timestamp = date('Y-m-d H:i:s');

			if ($model->save())
				return $this->redirect(['view', 'id' => $model->id, 'title' => $model->title]);
			else
				return $this->render('submit', ['model' => $model]);
		}
		else
			return $this->render('submit', ['model' => $model]);
	}

	public function actionVote($id, $title)
	{
		$model = new Vote;

		if ($model->load(Yii::$app->request->post()))
		{
			if ($model->times)
			{
				$item = Item::find()
					->select(['id','morning','afternoon','night','anytime'])
					->where('id=:id', [':id' => $id])
					->one();
				if (!$item)
					throw new NotFoundHttpException('The requested page does not exist.');

				if (count($model->times) === 3)
					$item->anytime += 1;
				else
					foreach ($model->times as $time)
						switch ($time)
						{
							case 'morning':
								$item->morning += 1;
								break;
							case 'afternoon':
								$item->afternoon += 1;
								break;
							case 'night':
								$item->night += 1;
								break;
						}

				if ($item->update(false))
					return $this->redirect(['view', 'id' => $id, 'title' => $title]);
				else
					return $this->render('vote.twig', [
						'model' => $model,
						'id' => $id,
						'title' => $title
					]);
			}
			else
				return $this->redirect(['view', 'id' => $id, 'title' => $title]);
		}
		else
			return $this->render('vote.twig', [
				'model' => $model,
				'id' => $id,
				'title' => $title
			]);
	}

	/**
	 * Updates an existing Item model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = Item::find()
			->select(['id','title','type'])
			->where('id=:id', [':id' => $id])
			->one();
		if (!$model)
			throw new NotFoundHttpException('The requested page does not exist.');

		$model->setScenario('update');

		if ($model->load(Yii::$app->request->post()) && $model->save())
			return $this->redirect(['view', 'id' => $model->id, 'title' => $model->title]);
		else
			return $this->render('update', ['model' => $model]);
	}

	/**
	 * Deletes an existing Item model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$model = Item::find()
			->select('id')
			->where('id=:id', [':id' => $id])
			->one();
		if (!$model)
			throw new NotFoundHttpException('The requested page does not exist.');

		$imageRows = (new Query)
			->select('file')
			->from(Image::tableName())
			->where('item_id=:item_id', [':item_id' => $id])
			->all();

		$images = [];

		foreach ($imageRows as $imageRow)
			if ($imageRow['file'])
				$images[] = $imageRow['file'];

		if ($model->delete())
			foreach ($images as $image)
			{
				unlink('uploads/'.$image);
				unlink('uploads/thumbnails/150x150_'.$image);
				unlink('uploads/thumbnails/64x64_'.$image);
			}

		return $this->redirect(['index']);
	}
}

views/site/contact.php
<?php

/* @var $this yii\web\View */

$this->title = 'Contact - '.Yii::$app->params['app'];
?>
<div class="site-contact">
	<h1>Contact</h1>

	<form method="POST" action="https://formspree.io/robrtknight@gmail.com" role="form" autocomplete="off">
		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" name="_replyto" class="form-control input-sm" id="email" placeholder="Enter email" required>
		</div>
		<div class="form-group">
			<label for="name">Name</label>
			<input type="text" name="name" class="form-control input-sm" id="name" placeholder="Enter name" required>
		</div>
		<div class="form-group">
			<label for="subject">Subject</label>
			<input type="text" name="subject" class="form-control input-sm" id="subject" placeholder="Enter subject" required>
		</div>
		<div class="form-group">
			<label for="message">Message</label>
			<textarea name="message" class="form-control input-sm" id="message" rows="6" placeholder="Enter message" required></textarea>
		</div>
		<input type="hidden" name="_subject" value="Contact - EatDrinkTime">
		<button type="submit" class="btn btn-primary btn-sm">Submit</button>
	</form>

</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

	<h1><?= Html::encode($this->title) ?></h1>

	<div class="alert alert-danger">
		<?= nl2br(Html::encode($message)) ?>
	</div>

	<p>
		The above error occurred while the Web server was processing your request.
	</p>
	<p>
		Please contact us if you think this is a server error. Thank you.
	</p>

</div>

views/site/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $chartItems */
/* @var $popularFoodItems */
/* @var $popularDrinkItems */
/* @var $recentItems */

$this->title = 'EatDrinkTime by Robert Knight';
?>

<?php $this->registerMetaTag(['name' => 'description', 'content' => 'A database-driven web site about consumption times.']) ?>
<?php $this->registerCssFile('//cdn.jsdelivr.net/morris.js/0.5.1/morris.css') ?>
<?php $this->registerJsFile('//cdn.jsdelivr.net/raphael/2.1.2/raphael-min.js', ['depends' => ['yii\web\JqueryAsset']]) ?>
<?php $this->registerJsFile('//cdn.jsdelivr.net/morris.js/0.5.1/morris.min.js', ['depends' => ['yii\web\JqueryAsset']]) ?>
<?php foreach ($chartItems as $i => $chartItem): ?>
	<?php $this->registerJS("
	new Morris.Donut({
		element: 'chart".$i."',
		data: [
			{ label: 'anytime', value: ".Html::encode($chartItem['anytime'])." },
			{ label: 'night', value: ".Html::encode($chartItem['night'])." },
			{ label: 'afternoon', value: ".Html::encode($chartItem['afternoon'])." },
			{ label: 'morning', value: ".Html::encode($chartItem['morning'])." }
		],
		resize: true,
		colors: ['#0A558F','#118EEE','#70BBF5','#CFE8FC']
	});
	");
	?>
<?php endforeach ?>

<div class="site-index">

<?php if (!Yii::$app->user->isGuest): ?>
	<p class='pull-right'>
		<?= Html::a('Items', ['item/index'], ['class' => 'btn btn-purple']) ?>
		<?= Html::a('Images', ['image/index'], ['class' => 'btn btn-black']) ?>
		<?= Html::a('Links', ['item-item/index'], ['class' => 'btn btn-warning']) ?>
	</p>
<?php endif ?>

	<section class="jumbotron">
		<h1>A database of consumption times.</h1>
		<p class="lead">Record what time you like to have your coffee or when is a good time for cake? Get insight to eat/drink patterns.</p>
		<?= Html::a('Submit item', ['item/submit'], ['class' => 'btn btn-success btn-lg']) ?>
	</section>

	<section>
		<h1>What time do people have:</h1>
		<div class='row'>
<?php foreach ($chartItems as $i => $chartItem): ?>
			<a href="<?= Html::encode(Url::to(['item/view', 'id' => $chartItem['id'], 'title' => $chartItem['title']])) ?>">
				<div class='pane col-md-2 col-sm-4 col-xs-12'>
					<h2><?= Html::encode($chartItem['title']) ?></h2>
					<div id="chart<?= $i ?>"></div>
				</div>
			</a>
<?php endforeach ?>
		</div>
	</section>

	<section>
		<h1>Most popular food items:</h1>
<?php if ($popularFoodItems): ?>
		<div class="row">
<?php foreach ($popularFoodItems as $id => $item): ?>
<?php $this->registerJS("$('#itemPF".Html::encode($id)."').tooltip();"); ?>
<?php if ($item->file): ?>
			<div class="col-sm-2 col-xs-6" id="itemPF<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($item->title) ?>">
				<a href="<?= Html::encode(Url::to(['item/view', 'id' => $id, 'title' => $item->title])) ?>" class="thumbnail">
					<img src="uploads/thumbnails/150x150_<?= Html::encode($item->file) ?>" alt='<?= Html::encode($item->title) ?>'>
				</a>
			</div>
<?php else: ?>
			<div class="col-sm-2 col-xs-6" id="itemPF<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($item->title) ?>">
				<a href="<?= Html::encode(Url::to(['item/view', 'id' => $id, 'title' => $item->title])) ?>" class="thumbnail">
					<img src='placeholder.png' alt='No Image'>
				</a>
			</div>
<?php endif ?>
<?php endforeach ?>
		</div>
<?php endif ?>
	</section>

	<section>
	<h1>Most popular drink items:</h1>
<?php if ($popularDrinkItems): ?>
	<div class="row">
<?php foreach ($popularDrinkItems as $id => $item): ?>
<?php $this->registerJS("$('#itemPD".Html::encode($id)."').tooltip();"); ?>
<?php if ($item->file): ?>
		<div class="col-sm-2 col-xs-6" id="itemPD<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($item->title) ?>">
			<a href="<?= Html::encode(Url::to(['item/view', 'id' => $id, 'title' => $item->title])) ?>" class="thumbnail">
				<img src="uploads/thumbnails/150x150_<?= Html::encode($item->file) ?>" alt='<?= Html::encode($item->title) ?>'>
			</a>
		</div>
<?php else: ?>
		<div class="col-sm-2 col-xs-6" id="itemPD<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($item->title) ?>">
			<a href="<?= Html::encode(Url::to(['item/view', 'id' => $id, 'title' => $item->title])) ?>" class="thumbnail">
				<img src='placeholder.png' alt='No Image'>
			</a>
		</div>
<?php endif ?>
<?php endforeach ?>
	</div>
<?php endif ?>
	</section>

	<section>
		<h1>Most recent items:</h1>
<?php if ($recentItems): ?>
		<div class="row">
<?php foreach ($recentItems as $id => $item): ?>
<?php $this->registerJS("$('#itemR".Html::encode($id)."').tooltip();"); ?>
<?php if ($item->file): ?>
			<div class="col-md-1 col-sm-2 col-xs-6" id="itemR<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($item->title) ?>">
				<a href="<?= Html::encode(Url::to(['item/view', 'id' => $id, 'title' => $item->title])) ?>" class="thumbnail">
					<img src="uploads/thumbnails/150x150_<?= Html::encode($item->file) ?>" alt='<?= Html::encode($item->title) ?>'>
				</a>
			</div>
<?php else: ?>
			<div class="col-md-1 col-sm-2 col-xs-6" id="itemR<?= Html::encode($id) ?>" data-toggle='tooltip' title="<?= Html::encode($item->title) ?>">
				<a href="<?= Html::encode(Url::to(['item/view', 'id' => $id, 'title' => $item->title])) ?>" class="thumbnail">
					<img src='placeholder.png' alt='No Image'>
				</a>
			</div>
<?php endif ?>
<?php endforeach ?>
		</div>
<?php endif ?>
	</section>

</div>

views/site/secure-signin.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Secure Signin - '.Yii::$app->params['app'];
?>
<?php $this->registerMetaTag(['name' => 'robots', 'content' => 'noindex']) ?>
<?php $this->registerMetaTag(['http-equiv' => 'X-UA-Compatible', 'content' => 'IE=Edge'], 'IE-Edge'); ?>
<?php $this->registerJsFile('//login.persona.org/include.js'); ?>
<?php	$this->registerJS('
$("#persona-btn").click(function(event) {
	event.preventDefault();
	navigator.id.request();
});

navigator.id.watch({
	loggedInUser: null,
	onlogin: function(assertion) {
		$.post(
			"'.Html::encode(Url::to(['secure-signin'])).'",
			{ assertion: assertion }
		);
	},
	onlogout: function() {}
});
', $this::POS_END, 'persona');
?>

<div class="site-secure-signin">
	<h1>Secure Signin</h1>
	<a id='persona-btn' href='#'><img src='persona.gif'></a>
</div>

views/site/super-secret-login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Super Secret Login - '.Yii::$app->params['app'];
?>
<?php $this->registerMetaTag(['name' => 'robots', 'content' => 'noindex']) ?>

<div class="site-super-secret-login">
	<h1>Super Secret Login</h1>

	<?php $form = ActiveForm::begin([
		'id' => 'login-form',
		'options' => ['class' => 'form-horizontal', 'autocomplete' => 'off'],
		'fieldConfig' => [
			'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
			'labelOptions' => ['class' => 'col-lg-1 control-label'],
		],
	]); ?>

	<?= $form->field($model, 'username') ?>

	<?= $form->field($model, 'password')->passwordInput() ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		</div>
	</div>

	<?php ActiveForm::end(); ?>
</div>